version: '3.8'
services:
  postgres:
    image: postgres
    container_name: nest-postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: nest
      POSTGRES_USER: nest
      POSTGRES_DB: nest
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
volumes:
  postgres:
    name: nest-db
